[build]
  # No build command needed for static site
  publish = "."

[build.environment]
  # Environment variables for build process
  NODE_VERSION = "18"

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  # Cache headers for assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache headers for PDFs
  for = "/*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  # Redirect non-www to www
  from = "https://andysquire.ai/*"
  to = "https://www.andysquire.ai/:splat"
  status = 301
  force = true

[[redirects]]
  # Redirect HTTP to HTTPS
  from = "http://www.andysquire.ai/*"
  to = "https://www.andysquire.ai/:splat"
  status = 301
  force = true

# Form handling (if needed for future contact forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

